# Generated by Django 4.1 on 2023-01-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iec',
            old_name='complete',
            new_name='issued',
        ),
    ]
