# Generated by Django 4.1 on 2023-01-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iec', '0004_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='iec',
            name='thematic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='thematic'),
        ),
        migrations.AlterField(
            model_name='iec',
            name='copies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='iec',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
